import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import { Container, Theme } from '@radix-ui/themes';
import AuthProvider from './providers/AuthProvider'
import QueryProvider from './providers/QueryProvider'
import { Toaster } from 'react-hot-toast'

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body >
        <QueryProvider>
          <AuthProvider>
            <Theme>
              <NavBar />
              <main className='p-5'>
                <Container>{children}</Container>
                <Toaster />
              </main>
            </Theme>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
